---
title: "All_sequential"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
"false"<=FALSE
"true"<=TRUE

knitr::opts_current$set(cache = TRUE, warning = FALSE,message = FALSE, cache.lazy = FALSE)
```


```{r, message=FALSE}
# Package names
packages <- c("ggrepel", "pheatmap", "DOSE", "clusterProfiler", "ensembldb", "annotables", "apeglm", "RColorBrewer", "vsn", "DESeq2", "ggplot2", "reshape2", "gage", "gageData", "AnnotationDbi", "tidyr", "dplyr", "org.Mm.eg.db", "gplots", "GO.db", "GOstats", "AnnotationHub", "pathview", "plyr", "tidyverse", "purrr", "GSEABase", "igraph", "vissE", "patchwork", "msigdb", "tibble", "msigdbr","fgsea", "GEOquery","EnhancedVolcano","ggvenn","readxl","msigdbr","Biobase")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  BiocManager::install(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

```{r}
countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24sig_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1:4,14:16)]
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld0=rlog(dds)
p0=plotPCA(rld, intgroup=c("treatment"))

normalized_counts0=counts(dds, normalized=TRUE)


res_table0=results(dds, contrast = c("treatment", "WT", "KO"))

normalized_counts0=counts(dds, normalized=TRUE)



res_table0_tb <- res_table0 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()



sig0 <- res_table0_tb[which(res_table0_tb[,7]<0.05),]


normalized_counts_c0=counts(dds, normalized=TRUE)


normalized_counts_c0 <- normalized_counts_c0 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig0 <- normalized_counts_c0[,] %>% 
              dplyr::filter(normalized_counts_c0$gene %in% sig0$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 

pdf("PCA0.pdf")
print(p0)
dev.off()

```




```{r}

EnhancedVolcano(res_table0,lab = rownames(res_table0),x = 'log2FoldChange',y = 'padj', title = 'WT vs KO time 0', FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}


hea0=pheatmap(norm_sig0, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))

pdf("heatmap0.pdf", height = 27)
print(hea0)
dev.off()

```






```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table0)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table0_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig0 <- dplyr::filter(res_ids, padj < 0.05)

sig0_genes <- as.character(sig0$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
zero_foldchanges <- res_entrez$log2FoldChange
names(zero_foldchanges) <- res_entrez$entrez
zero_foldchanges <- sort(zero_foldchanges, decreasing = TRUE)




zero_foldchanges=sort(zero_foldchanges,decreasing=TRUE)


gse0 <- gseGO(gene = zero_foldchanges, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL")





go0=dotplot(gse0, showCategory=10, split=".sign") + facet_grid(.~.sign)



gseaplot(gse0, by = "all", title = gse0$Description[1], geneSetID = 1)




ids<-bitr(rownames(norm_sig0), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table0_tb[res_table0_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


kk2 <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", nPerm = 10000, minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")

dotplot(kk2, showCategory = 20, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)



pdf("GO_GSEA_KEGG0.pdf")
print(go0)
print(kk2)
dev.off()

```









----------












```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1, 4:6,17:19)]
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld=vst(dds)
plotPCA(rld, intgroup=c("treatment"))

#normalized_counts4=counts(dds, normalized=TRUE)

normalized_counts4=rld




res_table4=results(dds, contrast = c("treatment", "WT", "KO"),alpha = 0.05)


normalized_counts4=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table4_tb <- res_table4 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig4 <- res_table4_tb[which(res_table4_tb[,7]<0.05),]


normalized_counts_c4=counts(dds, normalized=TRUE)


normalized_counts_c4 <- normalized_counts_c4 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig4 <- normalized_counts_c4[,] %>% 
              dplyr::filter(normalized_counts_c4$gene %in% sig4$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 
```




```{r}

EnhancedVolcano(res_table4,lab = rownames(res_table4),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}

hea4=pheatmap(norm_sig4, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))


pdf("heatmap0.pdf", height = 27)
print(hea4)
dev.off()
```











```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table4)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table4_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig4 <- dplyr::filter(res_ids, padj < 0.05)

sig4_genes <- as.character(sig4$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
four_foldchanges <- res_entrez$log2FoldChange
names(four_foldchanges) <- res_entrez$entrez
four_foldchanges <- sort(four_foldchanges, decreasing = TRUE)




four_foldchanges=sort(four_foldchanges,decreasing=TRUE)


gse4 <- gseGO(gene = four_foldchanges, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL")




go4=dotplot(gse4, showCategory=10, split=".sign") + facet_grid(.~.sign)



gseaplot(gse4, by = "all", title = gse4$Description[1], geneSetID = 1)




ids<-bitr(rownames(norm_sig4), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table4_tb[res_table4_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


kk2 <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", nPerm = 10000, minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")

dotplot(kk2, showCategory = 20, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)



pdf("GO_GSEA_KEGG4.pdf")
print(go4)
print(kk2)
dev.off()

```








------------------







```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1,8:10,20:22)]
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld=vst(dds)
plotPCA(rld, intgroup=c("treatment"))

#normalized_counts8=counts(dds, normalized=TRUE)

normalized_counts8=rld



res_table8=results(dds, contrast = c("treatment", "WT", "KO"),)



normalized_counts8=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table8_tb <- res_table8 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig8 <- res_table8_tb[which(res_table8_tb[,7]<0.05),]


normalized_counts_c8=counts(dds, normalized=TRUE)


normalized_counts_c8 <- normalized_counts_c8 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig8 <- normalized_counts_c8[,] %>% 
              dplyr::filter(normalized_counts_c8$gene %in% sig8$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 
```




```{r}

EnhancedVolcano(res_table8,lab = rownames(res_table8),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}
hea8=pheatmap(norm_sig8, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))

pdf("heatmap8.pdf")
print(hea8)
dev.off()
```




```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table8)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table8_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig8 <- dplyr::filter(res_ids, padj < 0.05)

sig8_genes <- as.character(sig8$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
eight_foldchanges <- res_entrez$log2FoldChange
names(eight_foldchanges) <- res_entrez$entrez
eight_foldchanges <- sort(eight_foldchanges, decreasing = TRUE)




eight_foldchanges=sort(eight_foldchanges,decreasing=TRUE)


gse8 <- gseGO(gene = eight_foldchanges, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL")





go8=dotplot(gse8, showCategory=10, split=".sign") + facet_grid(.~.sign)



gseaplot(gse8, by = "all", title = gse8$Description[1], geneSetID = 1)




ids<-bitr(rownames(norm_sig8), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table8_tb[res_table8_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


kk2 <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")

dotplot(kk2, showCategory = 20, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)




pdf("GO_GSEA_KEGG8.pdf")
print(go8)
print(kk2)
dev.off()
```


----------









```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1,11:13,23:24)]
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>50,]
sizeFactors(dds)
rld=vst(dds)
plotPCA(rld, intgroup=c("treatment"))

#normalized_counts24=counts(dds, normalized=TRUE)

normalized_counts24=rld




res_table24=results(dds, contrast = c("treatment", "WT", "KO"),alpha = 0.05)


normalized_counts24=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table24_tb <- res_table24 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig24 <- res_table24_tb[which(res_table24_tb[,7]<0.05),]


normalized_counts_c24=counts(dds, normalized=TRUE)


normalized_counts_c24 <- normalized_counts_c24 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig24 <- normalized_counts_c24[,] %>% 
              dplyr::filter(normalized_counts_c24$gene %in% sig24$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 

```




```{r}

EnhancedVolcano(res_table24,lab = rownames(res_table24),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}

hea24=pheatmap(norm_sig24, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))


pdf("heatmap24.pdf", height = 27)
print(hea24)
dev.off()
```



```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table24)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table24_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig24 <- dplyr::filter(res_ids, padj < 0.05)

sig24_genes <- as.character(sig24$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
twentyfour_foldchanges <- res_entrez$log2FoldChange
names(twentyfour_foldchanges) <- res_entrez$entrez
twentyfour_foldchanges <- sort(twentyfour_foldchanges, decreasing = TRUE)




twentyfour_foldchanges=sort(twentyfour_foldchanges,decreasing=TRUE)


gse24 <- gseGO(gene = twentyfour_foldchanges, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL")



go24=dotplot(gse24, showCategory=10, split=".sign") + facet_grid(.~.sign)




gseaplot(gse24, by = "all", title = gse24$Description[1], geneSetID = 1)




ids<-bitr(rownames(norm_sig24), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table24_tb[res_table24_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


kk2 <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", nPerm = 10000, minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")

dotplot(kk2, showCategory = 20, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)



pdf("GO_GSEA_KEGG24.pdf")
print(go24)
print(kk2)
dev.off()
```






----------








```{r}






ggvenn(list("24"=sig24$gene, "8"=sig8$gene,"4"=sig4$gene))

three_cond=intersect(intersect(sig24$gene,sig8$gene),sig4$gene)
three_cond
eight_n_four=intersect(sig4$gene,sig8$gene)
eight_n_four
eight_n_twentyfour=intersect(sig8$gene,sig24$gene)
eight_n_twentyfour
four_n_twentyfour=intersect(sig4$gene,sig24$gene)
four_n_twentyfour
write.csv(four_n_twentyfour,"four_n_twentyfour.csv")
```






```{r}


countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1,5:13,17:24)]
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","WT","WT","WT","WT","WT","WT","KO","KO","KO","KO","KO","KO","KO","KO")
timee=c(rep("4",3),rep("8",3),rep("24",3),rep("4",3),rep("8",3),rep("24",2))
#colData=as_tibble(cbind(colnames(countData),time,treatment))


colData=as_tibble(cbind(colnames(countData),treatment,timee))
colData$group=str_c(treatment,timee)
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~timee+treatment+timee*treatment)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>50,]
sizeFactors(dds)
rld=vst(dds)
plotPCA(rld, intgroup=c("treatment"))


res_table=results(dds)

normalized_counts=counts(dds, normalized=TRUE)



res_table_tb <- res_table %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()



sig <- res_table_tb[which(res_table_tb[,7]<0.05),]


normalized_counts_c=counts(dds, normalized=TRUE)


normalized_counts_c <- normalized_counts_c %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig <- normalized_counts_c[,] %>% 
              dplyr::filter(normalized_counts_c$gene %in% sig$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 




```




```{r}
pheatmap(norm_sig, scale = "row", clustering_distance_rows = "correlation", fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))



```






```{r}


normalized_counts=counts(dds, normalized=TRUE)





normalized_counts <- normalized_counts %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

normalized_counts$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")

normalized_counts$gene=normalized_counts$entrez

normalized_counts=normalized_counts[,1:18]

normalized_counts=aggregate(. ~gene , data = normalized_counts, sum)

normalized_counts <- normalized_counts %>%
  data.frame() %>%
 column_to_rownames(var = "gene")


require(Biobase)
normalized_counts1<-new("ExpressionSet", exprs=as.matrix(normalized_counts))


normalized_counts1$time= colData$group




pathwaysDF <- msigdbr("mouse", category=c("H"))
pathways <- split(as.character(pathwaysDF$entrez_gene), pathwaysDF$gs_name)


set.seed(1)
gesecaRes <- geseca(pathways, exprs(normalized_counts1), minSize = 10, maxSize = 1000, eps = 0)

plotGesecaTable(gesecaRes |> head(50), pathways,E=exprs(normalized_counts1),)

plotCoregulationProfile(pathway=pathways[["HALLMARK_GLYCOLYSIS"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


plotCoregulationProfile(pathway=pathways[["HALLMARK_INFLAMMATORY_RESPONSE"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


plotCoregulationProfile(pathway=pathways[["HALLMARK_FATTY_ACID_METABOLISM"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


plotCoregulationProfile(pathway=pathways[["HALLMARK_HYPOXIA"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)



```










```{r}
data("go.sets.mm")
data("go.subs.mm")
```


```{r}
go_bp_sets=go.sets.mm[go.subs.mm$BP]
go_bp_res=gage(exprs=zero_foldchanges, gsets=go.sets.mm, same.dir = TRUE)
```


```{r}
data("kegg.sets.mm")
data("sigmet.idx.mm")
kegg.sets.mm=kegg.sets.mm[sigmet.idx.mm]

```

```{r}
keggres=gage(exprs=zero_foldchanges, gsets = kegg.sets.mm, same.dir = TRUE)
keggrespathways_greater=data.frame(id=rownames(keggres$greater), keggres$greater) %>%
  tibble::as_tibble() %>%
  filter(row_number() <= 50) %>%
  .$id %>%
  as.character()
keggrespathways_greater
```

```{r}
keggrespathways_lower=data.frame(id=rownames(keggres$less),
  keggres$less) %>%
  tibble::as_tibble() %>%
  filter(row_number() <= 50) %>%
  .$id %>%
  as.character()
keggrespathways_lower
```

```{r}
keggresids=substr(keggrespathways_greater, start=1, stop=8)
keggresids
```


```{r}
##tmp=sapply(keggresids, function(pid) pathview(gene.data = foldchanges, pathway.id = pid, species = "mmu"))


gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "ENSEMBL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")


```





```{r}


countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=aggregate(. ~gene_id , data = countData, sum)
#countData <- tibble::column_to_rownames(countData, "simple")
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","KO","KO","KO","KO","KO","KO","KO","KO","KO","KO","KO")
timee=c(rep("0",3),rep("4",3),rep("8",3),rep("24",3),rep("0",3),rep("4",3),rep("8",3),rep("24",2))
#colData=as_tibble(cbind(colnames(countData),time,treatment))


colData=as_tibble(cbind(colnames(countData),treatment,timee))
colData$group=str_c(treatment,timee)
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~timee+treatment)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>50,]
sizeFactors(dds)
rld=vst(dds)
plotPCA(rld, intgroup=c("treatment"))


res_table=results(dds)

normalized_counts=counts(dds, normalized=TRUE)



res_table_tb <- res_table %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()



sig <- res_table_tb[which(res_table_tb[,7]<0.05),]


normalized_counts_c=counts(dds, normalized=TRUE)


normalized_counts_c <- normalized_counts_c %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig <- normalized_counts_c[,] %>% 
              dplyr::filter(normalized_counts_c$gene %in% sig$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 




```


```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
all_foldchanges <- res_entrez$log2FoldChange
names(all_foldchanges) <- res_entrez$entrez
all_foldchanges <- sort(all_foldchanges, decreasing = TRUE)




all_foldchanges=sort(all_foldchanges,decreasing=TRUE)


gse <- gseGO(gene = all_foldchanges, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL")





dotplot(gse, showCategory=10, split=".sign") + facet_grid(.~.sign)




gseaplot(gse, by = "all", title = gse$Description[1], geneSetID = 1)




ids<-bitr(rownames(norm_sig), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table_tb[res_table_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)


kk2 <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", nPerm = 10000, minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")


```



