---
title: "All_sequential"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
"false"<=FALSE
"true"<=TRUE

knitr::opts_current$set(cache = TRUE, warning = FALSE,message = FALSE, cache.lazy = FALSE)
```


```{r, message=FALSE}
# Package names
packages <- c("ggrepel", "pheatmap", "DOSE", "clusterProfiler", "ensembldb", "annotables", "apeglm", "RColorBrewer", "vsn", "DESeq2", "ggplot2", "reshape2", "gage", "gageData", "AnnotationDbi", "tidyr", "dplyr", "org.Mm.eg.db", "gplots", "GO.db", "GOstats", "AnnotationHub", "pathview", "plyr", "tidyverse", "purrr", "GSEABase", "igraph", "vissE", "patchwork", "msigdb", "tibble", "msigdbr","fgsea", "GEOquery","EnhancedVolcano","ggvenn","readxl","msigdbr","Biobase")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  BiocManager::install(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

```{r}
countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24sig_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1:4,14:16)]
countData=aggregate(. ~gene_id , data = countData, sum)
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld0=rlog(dds)
p0=plotPCA(rld0, intgroup=c("treatment"))

normalized_counts0=counts(dds, normalized=TRUE)


res_table0=results(dds, contrast = c("treatment", "WT", "KO"))

normalized_counts0=counts(dds, normalized=TRUE)



res_table0_tb <- res_table0 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()



sig0 <- res_table0_tb[which(res_table0_tb[,7]<0.05 & abs(res_table0_tb[,3])>1.5),]



normalized_counts_c0=counts(dds, normalized=TRUE)


normalized_counts_c0 <- normalized_counts_c0 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig0 <- normalized_counts_c0[,] %>% 
              dplyr::filter(normalized_counts_c0$gene %in% sig0$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 

pdf("PCA0.pdf")
print(p0)
dev.off()

```




```{r}

EnhancedVolcano(res_table0,lab = rownames(res_table0),x = 'log2FoldChange',y = 'padj', title = 'WT vs KO time 0', FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}


hea0=pheatmap(norm_sig0, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))

pdf("heatmap0.pdf", height = 27)
print(hea0)
dev.off()

```





```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table0)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table0_tb, ids, by=c("gene"="symbol"))     

zero_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes0 <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
zero_foldchanges <- res_entrez$log2FoldChange
names(zero_foldchanges) <- res_entrez$entrez
zero_foldchanges <- sort(zero_foldchanges, decreasing = TRUE)

symbol_foldchanges=sig$log2FoldChange

names(symbol_foldchanges)=sig$gene


zero_foldchanges=sort(zero_foldchanges,decreasing=TRUE)



go0 <- enrichGO(gene = sig_genes0, 
                universe = zero_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL", 
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.05, 
                readable = TRUE)






go_dp0=dotplot(go0, showCategory=32)



netplot0=cnetplot(go0, foldchange=zero_foldchanges0)


ids<-bitr(rownames(norm_sig0), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table0_tb[res_table0_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list0 <- df2$log2FoldChange

names(kegg_gene_list0) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list0)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list0 = sort(kegg_gene_list0, decreasing = TRUE)



gse0 <- gseGO(gene = kegg_gene_list0, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL",     pAdjustMethod = "BH",)

gsea0=dotplot(gse0, showCategory=10)

gseap0=gseaplot(gse0, by = "all", title = gse$Description[1], geneSetID = 1)


kgg0 <- gseKEGG(geneList= kegg_gene_list0, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")



kegg=dotplot(kgg0)


pdf("GO_dotplot0.pdf", height=13)
print(go_dp0)
dev.off()


pdf("gsea_plot0.pdf")
print(gseap0)
dev.off()

pdf("gsea_dotplot0.pdf")
print(gsea0)
dev.off()


pdf("kegg_dotplot0.pdf")
print(kegg)
dev.off()


pdf("network0.pdf",width = 10)
print(netplot0)
dev.off()






```









----------












```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1, 4:6,17:19)]
countData=aggregate(. ~gene_id , data = countData, sum)
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld=vst(dds)
p4=plotPCA(rld, intgroup=c("treatment"))

#normalized_counts4=counts(dds, normalized=TRUE)

normalized_counts4=rld




res_table4=results(dds, contrast = c("treatment", "WT", "KO"),alpha = 0.05)


normalized_counts4=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table4_tb <- res_table4 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig4 <- res_table4_tb[which(res_table4_tb[,7]<0.05 & abs(res_table4_tb[,3])>1.5),]



normalized_counts_c4=counts(dds, normalized=TRUE)


normalized_counts_c4 <- normalized_counts_c4 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig4 <- normalized_counts_c4[,] %>% 
              dplyr::filter(normalized_counts_c4$gene %in% sig4$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 



pdf("PCA4.pdf")
print(p4)
dev.off()

```




```{r}

EnhancedVolcano(res_table4,lab = rownames(res_table4),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}

hea4=pheatmap(norm_sig4, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))


pdf("heatmap0.pdf", height = 27)
print(hea4)
dev.off()
```





```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table4)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table4_tb, ids, by=c("gene"="symbol"))     

four_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes4 <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
four_foldchanges <- res_entrez$log2FoldChange
names(four_foldchanges) <- res_entrez$entrez
four_foldchanges <- sort(four_foldchanges, decreasing = TRUE)

symbol_foldchanges=sig$log2FoldChange

names(symbol_foldchanges)=sig$gene


four_foldchanges=sort(four_foldchanges,decreasing=TRUE)



go4 <- enrichGO(gene = sig_genes4, 
                universe = four_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL", 
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.05, 
                readable = TRUE)






go_dp4=dotplot(go4, showCategory=32)



netplot4=cnetplot(go4, foldchange=four_foldchanges4)


ids<-bitr(rownames(norm_sig4), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table4_tb[res_table4_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list4 <- df2$log2FoldChange

names(kegg_gene_list4) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list4)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list4 = sort(kegg_gene_list4, decreasing = TRUE)



gse4 <- gseGO(gene = kegg_gene_list4, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL",     pAdjustMethod = "BH",)

gsea4=dotplot(gse4, showCategory=10)

gseap4=gseaplot(gse4, by = "all", title = gse$Description[1], geneSetID = 1)


kgg4 <- gseKEGG(geneList= kegg_gene_list4, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")



kegg=dotplot(kgg4)


pdf("GO_dotplot4.pdf", height=13)
print(go_dp4)
dev.off()


pdf("gsea_plot4.pdf")
print(gseap4)
dev.off()

pdf("gsea_dotplot4.pdf")
print(gsea4)
dev.off()


pdf("kegg_dotplot4.pdf")
print(kegg)
dev.off()


pdf("network4.pdf",width = 10)
print(netplot4)
dev.off()






```






------------




```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1,8:10,20:22)]
countData=aggregate(. ~gene_id , data = countData, sum)
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld=vst(dds)
p8=plotPCA(rld, intgroup=c("treatment"))

#normalized_counts8=counts(dds, normalized=TRUE)

normalized_counts8=rld



res_table8=results(dds, contrast = c("treatment", "WT", "KO"),)



normalized_counts8=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table8_tb <- res_table8 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig8 <- res_table8_tb[which(res_table8_tb[,7]<0.05 & abs(res_table8_tb[,3])>1.5),]


normalized_counts_c8=counts(dds, normalized=TRUE)


normalized_counts_c8 <- normalized_counts_c8 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig8 <- normalized_counts_c8[,] %>% 
              dplyr::filter(normalized_counts_c8$gene %in% sig8$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 



pdf("PCA8.pdf")
print(p8)
dev.off()

```




```{r}

EnhancedVolcano(res_table8,lab = rownames(res_table8),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}
hea8=pheatmap(norm_sig8, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))

pdf("heatmap8.pdf")
print(hea8)
dev.off()
```



```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table8)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table8_tb, ids, by=c("gene"="symbol"))     

eight_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes8 <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
eight_foldchanges <- res_entrez$log2FoldChange
names(eight_foldchanges) <- res_entrez$entrez
eight_foldchanges <- sort(eight_foldchanges, decreasing = TRUE)

symbol_foldchanges=sig$log2FoldChange

names(symbol_foldchanges)=sig$gene


eight_foldchanges=sort(eight_foldchanges,decreasing=TRUE)



go8 <- enrichGO(gene = sig_genes8, 
                universe = eight_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL", 
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.05, 
                readable = TRUE)






go_dp8=dotplot(go8, showCategory=32)



netplot8=cnetplot(go8, foldchange=eight_foldchanges8)


ids<-bitr(rownames(norm_sig8), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table8_tb[res_table8_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list8 <- df2$log2FoldChange

names(kegg_gene_list8) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list8)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list8 = sort(kegg_gene_list8, decreasing = TRUE)



gse8 <- gseGO(gene = kegg_gene_list8, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL",     pAdjustMethod = "BH",)

gsea8=dotplot(gse8, showCategory=10)

gseap8=gseaplot(gse8, by = "all", title = gse$Description[1], geneSetID = 1)


kgg8 <- gseKEGG(geneList= kegg_gene_list8, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")



kegg=dotplot(kgg8)


pdf("GO_dotplot8.pdf", height=13)
print(go_dp8)
dev.off()


pdf("gsea_plot8.pdf")
print(gseap8)
dev.off()

pdf("gsea_dotplot8.pdf")
print(gsea8)
dev.off()


pdf("kegg_dotplot8.pdf")
print(kegg)
dev.off()


pdf("network8.pdf",width = 10)
print(netplot8)
dev.off()

```







----------









```{r}

countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=countData[,c(1,11:13,23:24)]
countData=aggregate(. ~gene_id , data = countData, sum)
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","KO","KO")
colData=as_tibble(cbind(colnames(countData),treatment))
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~treatment)
dds=estimateSizeFactors(dds)
sizeFactors(dds)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>5,]
sizeFactors(dds)
rld=vst(dds)
p24=plotPCA(rld, intgroup=c("treatment"))

#normalized_counts24=counts(dds, normalized=TRUE)

normalized_counts24=rld




res_table24=results(dds, contrast = c("treatment", "WT", "KO"),alpha = 0.05)


normalized_counts24=counts(dds, normalized=TRUE)


# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#   rownames_to_column(var="gene") %>% 
#   as_tibble()
# 
# normalized_counts0$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts0$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
# 
# normalized_counts0$gene=normalized_counts0$entrez
# 
# normalized_counts0=normalized_counts0[,1:7]
# 
# normalized_counts0=aggregate(. ~gene , data = normalized_counts0, sum)
# 
# normalized_counts0 <- normalized_counts0 %>%
#   data.frame() %>%
#  column_to_rownames(var = "gene")







res_table24_tb <- res_table24 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()




sig24 <- res_table24_tb[which(res_table24_tb[,7]<0.05 & abs(res_table24_tb[,3])>1.5),]


normalized_counts_c24=counts(dds, normalized=TRUE)


normalized_counts_c24 <- normalized_counts_c24 %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig24 <- normalized_counts_c24[,] %>% 
              dplyr::filter(normalized_counts_c24$gene %in% sig24$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene")


pdf("PCA24.pdf")
print(p24)
dev.off()


```




```{r}

EnhancedVolcano(res_table24,lab = rownames(res_table24),x = 'log2FoldChange',y = 'pvalue', title = 'WT vs KO time 0', pCutoff = 5e-2, FCcutoff = 1.5, pointSize = 2.0,labSize = 4.0)


```


```{r}

hea24=pheatmap(norm_sig24, scale = "row", clustering_distance_rows = "correlation", cutree_cols = 2, fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "0 h", cluster_cols = FALSE, gaps_col = c(3))


pdf("heatmap24.pdf", height = 27)
print(hea24)
dev.off()
```


```{r error=TRUE}
idx = grcm38$symbol %in% rownames(res_table24)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table24_tb, ids, by=c("gene"="symbol"))     

twentyfour_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes24 <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
twentyfour_foldchanges <- res_entrez$log2FoldChange
names(twentyfour_foldchanges) <- res_entrez$entrez
twentyfour_foldchanges <- sort(twentyfour_foldchanges, decreasing = TRUE)

symbol_foldchanges=sig$log2FoldChange

names(symbol_foldchanges)=sig$gene


twentyfour_foldchanges=sort(twentyfour_foldchanges,decreasing=TRUE)



go24 <- enrichGO(gene = sig_genes24, 
                universe = twentyfour_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL", 
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.05, 
                readable = TRUE)






go_dp24=dotplot(go24, showCategory=32)



netplot24=cnetplot(go24, foldchange=twentyfour_foldchanges24)


ids<-bitr(rownames(norm_sig24), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table24_tb[res_table24_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list24 <- df2$log2FoldChange

names(kegg_gene_list24) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list24)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list24 = sort(kegg_gene_list24, decreasing = TRUE)



gse24 <- gseGO(gene = kegg_gene_list24, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL",     pAdjustMethod = "BH",)

gsea24=dotplot(gse24, showCategory=10)

gseap24=gseaplot(gse24, by = "all", title = gse$Description[1], geneSetID = 1)


kgg24 <- gseKEGG(geneList= kegg_gene_list24, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")



kegg=dotplot(kgg24)


pdf("GO_dotplot24.pdf", height=13)
print(go_dp24)
dev.off()


pdf("gsea_plot24.pdf")
print(gseap24)
dev.off()

pdf("gsea_dotplot24.pdf")
print(gsea24)
dev.off()


pdf("kegg_dotplot24.pdf")
print(kegg)
dev.off()


pdf("network24.pdf",width = 10)
print(netplot24)
dev.off()

```






```{r}
venn3=ggvenn(list("24"=sig24$gene, "8"=sig8$gene,"4"=sig4$gene))
venn4=ggvenn(list("24"=sig24$gene, "8"=sig8$gene,"4"=sig4$gene,"0"=sig0$gene))
three_cond=intersect(intersect(sig24$gene,sig8$gene),sig4$gene)
write.csv(three_cond,"common_24_8_4.csv")
eight_n_four=intersect(sig4$gene,sig8$gene)
write.csv(eight_n_four, "common_8_4")
eight_n_twentyfour=intersect(sig8$gene,sig24$gene)
write.csv(eight_n_twentyfour, "common_8_24.csv")
four_n_twentyfour=intersect(sig4$gene,sig24$gene)
write.csv(four_n_twentyfour,"common_4_24.csv")
write.csv(four_n_twentyfour,"four_n_twentyfour.csv")
pdf("venn3.pdf")
print(venn3)
dev.off()
pdf("venn4.pdf")
print(venn4)
dev.off()




```