---
title: "Two_factors"
output:
  pdf_document: default
  always_allow_html: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
"false"<=FALSE
"true"<=TRUE

knitr::opts_current$set(cache = TRUE, warning = FALSE,message = FALSE, cache.lazy = FALSE)
```


```{r, message=FALSE}
# Package names
packages <- c("ggrepel", "pheatmap", "DOSE", "clusterProfiler", "ensembldb", "annotables", "apeglm", "RColorBrewer", "vsn", "DESeq2", "ggplot2", "reshape2", "gage", "gageData", "AnnotationDbi", "tidyr", "dplyr", "org.Mm.eg.db", "gplots", "GO.db", "GOstats", "AnnotationHub", "pathview", "plyr", "tidyverse", "purrr", "GSEABase", "igraph", "vissE", "patchwork", "msigdb", "tibble", "msigdbr","fgsea", "GEOquery","EnhancedVolcano","ggvenn","readxl","msigdbr","Biobase")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  BiocManager::install(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```






```{r}


countData <- read_excel("Gene_count_matrix_DEseq2_V4_NOT normalized.xlsx")
colnames(countData)=c("gene_id","WT0_1","WT0_2","WT0_3","WT4_1","WT4_2","WT4_3","WT8_1","WT8_2","WT8_3","WT24_1","WT24_2","WT24_3","KO0_1","KO0_2","KO0_3","KO4_1","KO4_2","KO4_3","KO8_1","KO8_2","KO8_3","KO24_1","KO24_2")
countData=aggregate(. ~gene_id , data = countData, sum)
countData=column_to_rownames(countData,'gene_id')
treatment=c("WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","WT","KO","KO","KO","KO","KO","KO","KO","KO","KO","KO","KO")
timee=c(rep("0",3),rep("4",3),rep("8",3),rep("24",3),rep("0",3),rep("4",3),rep("8",3),rep("24",2))
colData=as_tibble(cbind(colnames(countData),as.factor(treatment),as.factor(timee)))
colData$group=as.factor(str_c(treatment,timee))
colData$group=relevel(colData$group, ref = "WT0")
colnames(colData)[1]="samplename"
dds=DESeqDataSetFromMatrix(countData = countData, colData = colData, design = ~group)
dds=DESeq(dds)
dds =dds[rowSums(counts(dds))>50,]
sizeFactors(dds)
rld=vst(dds)
pca=plotPCA(rld, intgroup=c("group"))
resultsNames(dds)
res_table=results(dds, contrast=list(c("group_KO0_vs_WT0",  "group_KO24_vs_WT0", "group_KO4_vs_WT0"  ,"group_KO8_vs_WT0" , "group_WT24_vs_WT0", "group_WT4_vs_WT0",  "group_WT8_vs_WT0")))

normalized_counts=counts(dds, normalized=TRUE)


res_table_tb <- res_table %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()


sig <- res_table_tb[which(res_table_tb[,7]<0.05 & abs(res_table_tb[,3])>3),]







write.csv(res_table_tb,"all_DGE_and_stats.csv")

write.csv(res_table_tb$gene, "all_DGE_list.csv")


normalized_counts_c=counts(dds, normalized=TRUE)


normalized_counts_c <- normalized_counts_c %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

norm_sig <- normalized_counts_c[,] %>% 
              dplyr::filter(normalized_counts_c$gene %in% sig$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 






pdf("PCA.pdf")
print(pca)
dev.off()


pdf("dispest.pdf")
print(plotDispEsts(dds))
dev.off()

```



```{r}

#Remove unannotated genes ending in RIK
sig_red=sig[grep("*Rik", sig$gene, invert=TRUE),]


#Remove unnanotated genes starting with Gm
sig_red=sig_red[grep("Gm*", sig$gene, invert=TRUE),]


write.csv(sig_red$gene,"sig_red.csv")

sig_red=arrange(sig_red, desc(log2FoldChange))

sig_red=na.omit(sig_red)

top=head(sig_red,50)

bottom=tail(sig_red,50)

hundred_genes=full_join(top, bottom)


hun_norm_sig_red <- normalized_counts_c[,] %>% 
              dplyr::filter(normalized_counts_c$gene %in% hundred_genes$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 



norm_sig_red <- normalized_counts_c[,] %>% 
              dplyr::filter(normalized_counts_c$gene %in% sig_red$gene) %>%
	           data.frame() %>%
	           column_to_rownames(var = "gene") 


#Option 1
#Heatmap with all genes, useful to see all genes
phea=pheatmap(norm_sig_red, scale = "row", clustering_distance_rows = "correlation", fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "All times", cluster_cols = TRUE)

pdf("heatmap.pdf", height = 27)
print(phea)
dev.off()


a=sort(cutree(phea$tree_row, k=2))


write.csv(names(a[a==1]),"WT_only.csv")


write.csv(names(a[a==2]),"KO_only.csv")

#Option 2
#random sample of 300 genes, this preserves the natural clustering and avoids biases
phea_ran=pheatmap(slice_sample(norm_sig,n = 300), scale = "row", clustering_distance_rows = "correlation", fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "All times", cluster_cols = TRUE)


pdf("random_heatmap.pdf", height = 27)
print(phea_ran)
dev.off()



#Option 2

hun_phea=pheatmap(hun_norm_sig_red, scale = "row", clustering_distance_rows = "correlation", fontsize = 3, color = colorRampPalette(brewer.pal(9, "YlOrBr"))(255), cellwidth = 12.0, main = "All times", cluster_cols = TRUE)

pdf("top_bottom_50_heatmap.pdf")
print(hun_phea)
dev.off()

```


```{r error=TRUE}

idx = grcm38$symbol %in% rownames(res_table)

ids <- grcm38[idx, ]

non_duplicates <- which(duplicated(ids$symbol) == FALSE)

ids <- ids[non_duplicates, ] 

res_ids <- inner_join(res_table_tb, ids, by=c("gene"="symbol"))     

all_genes <- as.character(res_ids$entrez)

sig <- dplyr::filter(res_ids, padj < 0.05)

sig_genes <- as.character(sig$entrez)


res_entrez <- filter(res_ids, entrez != "NA")
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
all_foldchanges <- res_entrez$log2FoldChange
names(all_foldchanges) <- res_entrez$entrez
all_foldchanges <- sort(all_foldchanges, decreasing = TRUE)

symbol_foldchanges=sig$log2FoldChange

names(symbol_foldchanges)=sig$gene


all_foldchanges=sort(all_foldchanges,decreasing=TRUE)



go <- enrichGO(gene = sig_genes, 
                universe = all_genes,
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "ALL", 
                pAdjustMethod = "BH", 
                qvalueCutoff = 0.05, 
                readable = TRUE,maxGSSize = 250)






go_dp=dotplot(go, showCategory=60)



netplot=cnetplot(go, foldchange=all_foldchanges,fixed=F)


ids<-bitr(rownames(norm_sig), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Mm.eg.db)


dedup_ids = ids[!duplicated(ids[c("ENTREZID")]),]


df2 = res_table_tb[res_table_tb$gene %in% dedup_ids$SYMBOL,]

df2$Y = dedup_ids$ENTREZID


# Name vector with ENTREZ ids
kegg_gene_list <- df2$log2FoldChange

names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)



gse <- gseGO(gene = kegg_gene_list, 
                keyType = "ENTREZID",
                OrgDb = org.Mm.eg.db, 
                ont = "BP",     pAdjustMethod = "BH",eps = 0)

gsea=dotplot(gse, showCategory=50)


lapply(1:length(gse$Description), function(i) {gseaplot(gse, by = "all", title = gse$Description[i], geneSetID = i)})



pdf("gseas.pdf",width = 10)
print(lapply(1:length(gse$Description), function(i) {gseaplot(gse, by = "all", title = gse$Description[i], geneSetID = i)}))
dev.off()


kgg <- gseKEGG(geneList= kegg_gene_list, organism= "mmu", minGSSize    = 3,maxGSSize    = 1800, pvalueCutoff = 0.05,pAdjustMethod = "none",keyType= "kegg")



kegg=dotplot(kgg, showCategory=80)



a=lapply(1:10, function(x) {
   pathview(gene.data = foldchanges, pathway.id = kgg$ID[x], species = "mmu")})



pdf("GO_dotplot.pdf", width=10, height=33)
print(go_dp)
dev.off()



pdf("gsea_dotplot.pdf", width=10, height=33)
print(gsea)
dev.off()


pdf("kegg_dotplot.pdf", width=10, height=35)
print(kegg)
dev.off()


pdf("network.pdf", width=27, height=20)
print(netplot)
dev.off()





```





```{r}


normalized_counts=rlog(counts(dds))





normalized_counts <- normalized_counts %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

normalized_counts$entrez=mapIds(org.Mm.eg.db,key,keys = normalized_counts$gene,column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")

normalized_counts$gene=normalized_counts$entrez

normalized_counts=normalized_counts[,1:24]

normalized_counts=aggregate(. ~gene , data = normalized_counts, sum)

normalized_counts <- normalized_counts %>%
  data.frame() %>%
 column_to_rownames(var = "gene")


require(Biobase)
normalized_counts1<-new("ExpressionSet", exprs=as.matrix(normalized_counts))


normalized_counts1$time= colData$group




pathwaysDF <- msigdbr("mouse", category=c("H"))
pathways <- split(as.character(pathwaysDF$entrez_gene), pathwaysDF$gs_name)


set.seed(1)
gesecaRes <- geseca(pathways, exprs(normalized_counts1), minSize = 10, maxSize = 1000, eps = 0,nPermSimple = 10000)

geseres=plotGesecaTable(gesecaRes |> head(5), pathways,E=exprs(normalized_counts1),)

IFNG=plotCoregulationProfile(pathway=pathways[["HALLMARK_INTERFERON_GAMMA_RESPONSE"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


INF=plotCoregulationProfile(pathway=pathways[["HALLMARK_INFLAMMATORY_RESPONSE"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


TNF_NFKB=plotCoregulationProfile(pathway=pathways[["HALLMARK_TNFA_SIGNALING_VIA_NFKB"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)


TNFA=plotCoregulationProfile(pathway=pathways[["HALLMARK_INTERFERON_ALPHA_RESPONSE"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)

E2F=plotCoregulationProfile(pathway=pathways[["HALLMARK_E2F_TARGETS"]],
                        E=exprs(normalized_counts1), conditions=normalized_counts1$time)







fgseaRes <- fgsea(pathways = pathways, 
                  stats    = all_foldchanges,)


fgseaResTidy <- fgseaRes %>%
  as_tibble() %>%
  arrange(desc(NES))

# Show in a nice table:
fgseaResTidy %>% 
  dplyr::select(-leadingEdge, -ES) %>% 
  arrange(padj) %>% 
  DT::datatable()



fgsearesgraph=ggplot(fgseaResTidy, aes(reorder(pathway, NES), NES)) +
  geom_col(color=fgseaResTidy$NES>0) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") + 
  theme_minimal()



pdf("IFNG.pdf",width = 10)
print(IFNG)
dev.off()


pdf("INF.pdf",width = 10)
print(INF)
dev.off()


pdf("TNF_NFKB.pdf",width = 10)
print(TNF_NFKB)
dev.off()


pdf("TNFA.pdf",width = 10)
print(TNFA)
dev.off()


pdf("E2F.pdf",width = 10)
print(E2F)
dev.off()


pdf("geseca.pdf",width = 10)
print(geseres)
dev.off()



pdf("fgsearesgraph.pdf",width = 10)
print(fgsearesgraph)
dev.off()





```


